services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Slub\SlubProfileEvents\:
    resource: '../Classes/*'

  Slub\SlubProfileEvents\Service\ApiService:
    public: true

  Slub\SlubProfileEvents\Service\EventService:
    public: true
