services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Slub\SlubProfileEvents\:
    resource: '../Classes/*'

  Slub\SlubProfileEvents\Http\Request:
    public: true

  Slub\SlubProfileEvents\Routing\UriGenerator:
    public: true

  Slub\SlubProfileEvents\Service\EventService:
    public: true
